[[yolov3]]
name = 'yolov3-sppu_imgsz320_fp16'
head_in_tensor_names = []
head_out_tensor_names = ['output0']

[[yolov3]]
name = 'yolov3-sppu_imgsz640_fp16'
head_in_tensor_names = []
head_out_tensor_names = ['output0']

[[yolov3]]
name = 'yolov3-tinyu_imgsz320_fp16'
head_in_tensor_names = []
head_out_tensor_names = ['output0']

[[yolov3]]
name = 'yolov3-tinyu_imgsz640_fp16'
head_in_tensor_names = []
head_out_tensor_names = ['output0']

[[yolov3]]
name = 'yolov3u_imgsz320_fp16'
head_in_tensor_names = []
head_out_tensor_names = ['output0']

[[yolov3]]
name = 'yolov3u_imgsz640_fp16'
head_in_tensor_names = []
head_out_tensor_names = ['output0']

[[yolov5]]
name = 'yolov5m_imgsz320_fp16'
head_in_tensor_names = []
head_out_tensor_names = ['output0']

[[yolov5]]
name = 'yolov5m_imgsz640_fp16'
head_in_tensor_names = []
head_out_tensor_names = ['output0']

[[yolov5]]
name = 'yolov5n_imgsz320_fp16'
head_in_tensor_names = []
head_out_tensor_names = ['output0']

[[yolov5]]
name = 'yolov5n_imgsz640_fp16'
head_in_tensor_names = []
head_out_tensor_names = ['output0']

[[yolov5]]
name = 'yolov5s_imgsz320_fp16'
head_in_tensor_names = []
head_out_tensor_names = ['output0']

[[yolov5]]
name = 'yolov5s_imgsz640_fp16'
head_in_tensor_names = []
head_out_tensor_names = ['output0']

[[yolov8]]
name = 'yolov8m_imgsz320_fp16'
head_in_tensor_names = []
head_out_tensor_names = ['output0']

[[yolov8]]
name = 'yolov8m_imgsz640_fp16'
head_in_tensor_names = []
head_out_tensor_names = ['output0']

[[yolov8]]
name = 'yolov8n_imgsz320_fp16'
head_in_tensor_names = []
head_out_tensor_names = ['output0']

[[yolov8]]
name = 'yolov8n_imgsz640_fp16'
head_in_tensor_names = []
head_out_tensor_names = ['output0']

[[yolov8]]
name = 'yolov8s_imgsz320_fp16'
head_in_tensor_names = []
head_out_tensor_names = ['output0']

[[yolov8]]
name = 'yolov8s_imgsz640_fp16'
head_in_tensor_names = []
head_out_tensor_names = ['output0']